"""add logo_url to teams

Revision ID: 4626c6590349
Revises: 9e35537e7c6d
Create Date: 2026-06-10 08:09:42.235206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4626c6590349'
down_revision: Union[str, None] = '9e35537e7c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###
