"""add totp columns to users

Revision ID: 9e35537e7c6d
Revises: 3e10801dd8ae
Create Date: 2026-06-08 15:34:09.203037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e35537e7c6d'
down_revision: Union[str, None] = '3e10801dd8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'totp_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),   # gives existing rows a value
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
